name: Frontend SonarCloud

on:
  workflow_dispatch:
  push:
    branches: ["main", "staging", "develop"]
  pull_request:

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest
    if: ${{ secrets.SONAR_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
